<?php
/**
 * BroadbandKBDIpTestPacket
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BroadbandKBDIpTestPacket Class Doc Comment
 *
 * @category Class
 * @description BroadbandKBDIpTestPacket struct
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BroadbandKBDIpTestPacket implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BroadbandKBDIpTestPacket';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'upstream_initial' => 'string',
        'upstream_final' => 'string',
        'upstream_rate' => 'string',
        'downstream_initial' => 'string',
        'downstream_final' => 'string',
        'downstream_rate' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'upstream_initial' => null,
        'upstream_final' => null,
        'upstream_rate' => null,
        'downstream_initial' => null,
        'downstream_final' => null,
        'downstream_rate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'upstream_initial' => true,
		'upstream_final' => true,
		'upstream_rate' => true,
		'downstream_initial' => true,
		'downstream_final' => true,
		'downstream_rate' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'upstream_initial' => 'upstream_initial',
        'upstream_final' => 'upstream_final',
        'upstream_rate' => 'upstream_rate',
        'downstream_initial' => 'downstream_initial',
        'downstream_final' => 'downstream_final',
        'downstream_rate' => 'downstream_rate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'upstream_initial' => 'setUpstreamInitial',
        'upstream_final' => 'setUpstreamFinal',
        'upstream_rate' => 'setUpstreamRate',
        'downstream_initial' => 'setDownstreamInitial',
        'downstream_final' => 'setDownstreamFinal',
        'downstream_rate' => 'setDownstreamRate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'upstream_initial' => 'getUpstreamInitial',
        'upstream_final' => 'getUpstreamFinal',
        'upstream_rate' => 'getUpstreamRate',
        'downstream_initial' => 'getDownstreamInitial',
        'downstream_final' => 'getDownstreamFinal',
        'downstream_rate' => 'getDownstreamRate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('upstream_initial', $data ?? [], null);
        $this->setIfExists('upstream_final', $data ?? [], null);
        $this->setIfExists('upstream_rate', $data ?? [], null);
        $this->setIfExists('downstream_initial', $data ?? [], null);
        $this->setIfExists('downstream_final', $data ?? [], null);
        $this->setIfExists('downstream_rate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets upstream_initial
     *
     * @return string|null
     */
    public function getUpstreamInitial()
    {
        return $this->container['upstream_initial'];
    }

    /**
     * Sets upstream_initial
     *
     * @param string|null $upstream_initial Initial – IP Packet – Upstream.
     *
     * @return self
     */
    public function setUpstreamInitial($upstream_initial)
    {
        if (is_null($upstream_initial)) {
            array_push($this->openAPINullablesSetToNull, 'upstream_initial');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('upstream_initial', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['upstream_initial'] = $upstream_initial;

        return $this;
    }

    /**
     * Gets upstream_final
     *
     * @return string|null
     */
    public function getUpstreamFinal()
    {
        return $this->container['upstream_final'];
    }

    /**
     * Sets upstream_final
     *
     * @param string|null $upstream_final Final – IP Packet – Upstream.
     *
     * @return self
     */
    public function setUpstreamFinal($upstream_final)
    {
        if (is_null($upstream_final)) {
            array_push($this->openAPINullablesSetToNull, 'upstream_final');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('upstream_final', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['upstream_final'] = $upstream_final;

        return $this;
    }

    /**
     * Gets upstream_rate
     *
     * @return string|null
     */
    public function getUpstreamRate()
    {
        return $this->container['upstream_rate'];
    }

    /**
     * Sets upstream_rate
     *
     * @param string|null $upstream_rate IP Packet Rate – Upstream.
     *
     * @return self
     */
    public function setUpstreamRate($upstream_rate)
    {
        if (is_null($upstream_rate)) {
            array_push($this->openAPINullablesSetToNull, 'upstream_rate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('upstream_rate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['upstream_rate'] = $upstream_rate;

        return $this;
    }

    /**
     * Gets downstream_initial
     *
     * @return string|null
     */
    public function getDownstreamInitial()
    {
        return $this->container['downstream_initial'];
    }

    /**
     * Sets downstream_initial
     *
     * @param string|null $downstream_initial Initial – IP Packet – Downstream.
     *
     * @return self
     */
    public function setDownstreamInitial($downstream_initial)
    {
        if (is_null($downstream_initial)) {
            array_push($this->openAPINullablesSetToNull, 'downstream_initial');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('downstream_initial', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['downstream_initial'] = $downstream_initial;

        return $this;
    }

    /**
     * Gets downstream_final
     *
     * @return string|null
     */
    public function getDownstreamFinal()
    {
        return $this->container['downstream_final'];
    }

    /**
     * Sets downstream_final
     *
     * @param string|null $downstream_final Final – IP Packet – downstream.
     *
     * @return self
     */
    public function setDownstreamFinal($downstream_final)
    {
        if (is_null($downstream_final)) {
            array_push($this->openAPINullablesSetToNull, 'downstream_final');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('downstream_final', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['downstream_final'] = $downstream_final;

        return $this;
    }

    /**
     * Gets downstream_rate
     *
     * @return string|null
     */
    public function getDownstreamRate()
    {
        return $this->container['downstream_rate'];
    }

    /**
     * Sets downstream_rate
     *
     * @param string|null $downstream_rate IP Packet Rate – Downstream.
     *
     * @return self
     */
    public function setDownstreamRate($downstream_rate)
    {
        if (is_null($downstream_rate)) {
            array_push($this->openAPINullablesSetToNull, 'downstream_rate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('downstream_rate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['downstream_rate'] = $downstream_rate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


