<?php
/**
 * BroadbandDataTransferApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BroadbandDataTransferApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BroadbandDataTransferApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for broadbandDataTransferDailyUsernameGet
     *
     * Retrieves the daily data transfer usage for a broadband user for the current month.
     *
     */
    public function testBroadbandDataTransferDailyUsernameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDataTransferDailyUsernameYearMonthGet
     *
     * Retrieves the daily data transfer usage for a broadband user for the specified month and year.
     *
     */
    public function testBroadbandDataTransferDailyUsernameYearMonthGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDataTransferHourlyUsernameGet
     *
     * Retrieves the hourly data transfer usage for a broadband user for the current day.
     *
     */
    public function testBroadbandDataTransferHourlyUsernameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDataTransferHourlyUsernameYearMonthDayGet
     *
     * Retrieves the hourly data transfer usage for a broadband user for the specified day, month and year.
     *
     */
    public function testBroadbandDataTransferHourlyUsernameYearMonthDayGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDataTransferMonthlyGet
     *
     * Retrieves the monthly data transfer usage for all users for the current month.
     *
     */
    public function testBroadbandDataTransferMonthlyGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDataTransferMonthlyUsernameGet
     *
     * Retrieves the monthly data transfer usage for a broadband user for the current month.
     *
     */
    public function testBroadbandDataTransferMonthlyUsernameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDataTransferMonthlyUsernameYearMonthGet
     *
     * Retrieves the monthly data transfer usage for a broadband user for the specified month and year.
     *
     */
    public function testBroadbandDataTransferMonthlyUsernameYearMonthGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDataTransferMonthlyYearMonthGet
     *
     * Retrieves the monthly data transfer usage for all users for the specified month and year.
     *
     */
    public function testBroadbandDataTransferMonthlyYearMonthGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
