<?php
/**
 * BroadbandRIPEApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BroadbandRIPEApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BroadbandRIPEApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for broadbandRipePersonGet
     *
     * Retrieves the RIPE person contacts that have been created for broadband accounts assigned to the reseller.
     *
     */
    public function testBroadbandRipePersonGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandRipePersonPost
     *
     * Creates a RIPE person contact assigned to the reseller.
     *
     */
    public function testBroadbandRipePersonPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandRipePersonRipeNicHandleDelete
     *
     * Deletes the RIPE person contact details for a nic-handle.
     *
     */
    public function testBroadbandRipePersonRipeNicHandleDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandRipePersonRipeNicHandleGet
     *
     * Retrieves a RIPE person contact for a specific nic-handle that has been created for a broadband account assigned to the reseller.
     *
     */
    public function testBroadbandRipePersonRipeNicHandleGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandRipePersonRipeNicHandlePut
     *
     * Changes the RIPE person contact details for a nic-handle.
     *
     */
    public function testBroadbandRipePersonRipeNicHandlePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
