<?php
/**
 * BroadbandDiagnosticsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BroadbandDiagnosticsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BroadbandDiagnosticsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for broadbandDiagnosticsResultsUsernameTestIdGet
     *
     * Gets the results of complete diagnostics test for a certain user and test ID for a TTB line.
     *
     */
    public function testBroadbandDiagnosticsResultsUsernameTestIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDiagnosticsUsernameGet
     *
     * Carry out a TalkTalk diagnostics test on the user line.
     *
     */
    public function testBroadbandDiagnosticsUsernameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandKbdPost
     *
     * Carry out a Knowledge Based Diagnostics test on a BT Openreach line.
     *
     */
    public function testBroadbandKbdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandKbdResultUsernameGet
     *
     * Gets the results of complete KBD's for a certain user.
     *
     */
    public function testBroadbandKbdResultUsernameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
